clc;close all; clear;
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: G:\My Drive\mechatronics\analog_py_tests\test_data.csv
%
% Auto-generated by MATLAB on 18-May-2022 13:23:37

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
testdataa = readtable("G:\My Drive\mechatronics\analog_py_tests\test_dataa1.csv", opts);
clear opts

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
testdata = readtable("G:\My Drive\mechatronics\analog_py_tests\test_data1.csv", opts);
                
%% Clear temporary variables
clear opts
Fs = 125e3;
A = table2array(testdataa);
B = table2array(testdata);
A = A(1:500000,:);
figure;
subplot(4,1,1);
plot(A(:,1));
subplot(4,1,2);
plot(A(:,2));
subplot(4,1,3);
plot(A(:,3));
subplot(4,1,4);
plot(A(:,4));
figure;
plot(A(:,1));
hold;
plot(A(:,2));
plot(B)
axis([200020 200070 -4.75 -4.4])
%axis([499982 499992 -1.3 -.95])
%axis([168274 168290 -1.3 .1])
legend(['1';'2';'o'])