clc;close all; clear;
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: G:\My Drive\mechatronics\analog_py_tests\test_data.csv
%
% Auto-generated by MATLAB on 18-May-2022 13:23:37

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
% 1
%2 3
% Import the data
testdataa = readtable("G:\My Drive\mechatronics\analog_py_tests\test_dataa.csv", opts);
load('highpass.mat');
load('bandpass.mat');
load('lowpass.mat');
%% Clear temporary variables
clear opts
Fs = 500e3;
A = table2array(testdataa);
% A(:,1) = filter(highpass,1,A(:,1));
% A(:,2) = filter(highpass,1,A(:,2));
% A(:,3) = filter(highpass,1,A(:,3));
% 
% A(:,1) = filter(lowpass,1,A(:,1));
% A(:,2) = filter(lowpass,1,A(:,2));
% A(:,3) = filter(lowpass,1,A(:,3));

A(:,1) = filter(bandpass,1,A(:,1));
A(:,2) = filter(bandpass,1,A(:,2));
A(:,3) = filter(bandpass,1,A(:,3));

% A = A(100:490000,:);
figure;
subplot(4,1,1);
plot(A(:,1));
subplot(4,1,2);
plot(A(:,2));
subplot(4,1,3);
plot(A(:,3));
subplot(4,1,4);
plot(A(:,4));
figure;
plot(A(:,1));hold;
plot(A(:,2));
plot(A(:,3));
legend('1','2','3');


N = length(A(:,1));
n = 100;
energies = zeros(1,N/n);
for i = 1:N/n
	%i=4 for 19200 and i=8 for 44800 @ 125
	%i=2 for 19200 and i=4 for 44800 @ 50
	%i=3 for 16000 and i=7 for 48000 @ 100
	x = A((1+(i-1)*n):i*n,1);
	X = fft(x);
	avg_energy = mean(abs(X(3:6)));
	energies(i) = avg_energy;
end
energies = energies;


one_index = find(energies>=1);

n_index = one_index(1)

%n_index = 488;


index = 19282;
index = n_index*n+50
X1 = A(index:index+50,1);
X2 = A(index:index+50,2);
X3 = A(index:index+50,3);
figure;
N = length(X1);
freq = (0:N-1)*800000/N;
plot(freq,abs(fft(X1)));
figure;hold;
plot(X1);
plot(X2);
plot(X3);
legend('1','2','3');
y1 = fft(X1);
y2 = fft(X2);
y3 = fft(X3);
y1 = y1(2:25);
y2 = y2(2:25);
y3 = y3(2:25);
figure;hold;
plot(abs(y1))
plot(abs(y2))
plot(abs(y3))
[~,p1] = max(abs(y1));
[~,p2] = max(abs(y2));
[~,p3] = max(abs(y3));

t1 = angle(y1(p1));
t2 = angle(y2(p2));
t3 = angle(y3(p3));
t1
t2
t3
theta = atan2((t3-t2),(2*(t2-t1)))

% top = sign(t3-t2);
% bottom = sign(2*(t3-t1) - (t3-t2));
% if( top < 0 && bottom > 0)
% 		theta = theta+pi;
% end
% if( top > 0 && bottom > 0)
% 		theta = theta-pi;
% end
degrees = theta*180/pi

figure;hold;
plot(energies);
