clc;close all; clear;
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: G:\My Drive\mechatronics\analog_py_tests\test_dataf1.csv
%
% Auto-generated by MATLAB on 19-Jun-2022 23:41:36

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
testdataf1 = readtable("G:\My Drive\mechatronics\analog_py_tests\test_dataf1.csv", opts);


%% Clear temporary variables
clear opts
A = table2array(testdataf1);
figure;
subplot(3,1,1);
plot(A(:,1));
subplot(3,1,2);
plot(A(:,2));
subplot(3,1,3);
plot(A(:,3));