clc;close all; clear;
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: G:\My Drive\mechatronics\analog_py_tests\test_data.csv
%
% Auto-generated by MATLAB on 18-May-2022 13:23:37

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
testdata = readtable("G:\My Drive\mechatronics\analog_py_tests\test_data1.csv", opts);
testdata2 = readtable("G:\My Drive\mechatronics\analog_py_tests\test_data2.csv", opts);


%% Clear temporary variables
clear opts
Fs = 800e3;
A = table2array(testdata);
%A = A(2:end);
A2 = table2array(testdata2);
%A2 = A2(2:end);
t = 0:length(A)-1;
t = t/Fs;
plot(t,A);
hold;
plot(t,A2);
format longg
y = [sum(abs(A2(1:4:end))) sum(abs(A2(2:4:end))) sum(abs(A2(3:4:end))) sum(abs(A2(4:4:end)))]
i = find(y == min(y))
if i > 2
    k = -2;
else
    k = 2;
end
B1 = A(i+k:4:end);
B2 = A(i:4:end);
B3 = A2(i+k:4:end);
B4 = A2(i:4:end);
figure;
subplot(2,1,1);
plot(A(1:4:end));
hold;
plot(A(2:4:end));
plot(A(3:4:end));
plot(A(4:4:end));

%%phase shift occurs because of packet stitching
subplot(2,1,2);
plot(A2(1:4:end));
hold;
plot(A2(2:4:end));
plot(A2(3:4:end));
plot(A2(4:4:end));
t1 = (0:length(B1)-1)*4/(Fs);
t2 = (0:length(B2)-1)*4/(Fs);
figure;
subplot(4,1,1);
plot(t1,B1);
subplot(4,1,2);
plot(t2,B2);
subplot(4,1,3);
plot(t1,B3);
subplot(4,1,4);
plot(t2,B4);
%figure;
%plot((-length(B4)/2:length(B4)/2-1)*200000/length(B4),20*log10(abs(fftshift(fft(B4)))))

freq = (0:length(B1)-1)*500000/length(B1);
freq = freq(260000:300000);
fft1 = fft(B1);
fft1 = fft1(260000:300000);
fft2 = fft(B2);
fft2 = fft2(260000:300000);
fft3 = fft(B3);
fft3 = fft3(260000:300000);
fft4 = fft(B4);
fft4 = fft4(260000:300000);
figure;
subplot(4,1,1);
plot(freq,abs((fft1)));
subplot(4,1,2);
plot(freq,abs((fft2)));
subplot(4,1,3);
plot(freq,abs((fft3)));
subplot(4,1,4);
plot(freq,abs((fft4)));