close all;
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: G:\My Drive\mechatronics\analog_py_tests\test_dataj.csv
%
% Auto-generated by MATLAB on 19-Jun-2022 23:56:04

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
testdataj = readtable("G:\My Drive\mechatronics\analog_py_tests\test_dataj.csv", opts);


%% Clear temporary variables
clear opts
A = table2array(testdataj);
npfft = A(:,2)+i.*A(:,3);
%npfft = fftshift(npfft);
npfft = npfft(10800:end-10800);
sensor = A(:,1);
freq = (0:length(sensor)-1)*500000/length(sensor);
freq = freq(10800:end-10800);
%sensor = filter(Num,1,sensor);
mlfft = fft(sensor);
%mlfft = fftshift(mlfft);
mlfft = mlfft(10800:end-10800);
plot(freq,(abs(npfft)));
hold;
plot(freq,(abs(mlfft)));