clc;close all; clear;
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: G:\My Drive\mechatronics\analog_py_tests\test_data.csv
%
% Auto-generated by MATLAB on 18-May-2022 13:23:37

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
% 1
%2 3
% Import the data
testdataa = readtable("G:\My Drive\mechatronics\analog_py_tests\test_dataa.csv", opts);
load('highpass.mat');
load('lowpass.mat');
%% Clear temporary variables
clear opts
Fs = 500e3;
A = table2array(testdataa);
A(:,1) = filter(highpass,1,A(:,1));
A(:,2) = filter(highpass,1,A(:,2));
A(:,3) = filter(highpass,1,A(:,3));

A(:,1) = filter(lowpass,1,A(:,1));
A(:,2) = filter(lowpass,1,A(:,2));
A(:,3) = filter(lowpass,1,A(:,3));

% A = A(100:490000,:);
figure;
subplot(4,1,1);
plot(A(:,1));
subplot(4,1,2);
plot(A(:,2));
subplot(4,1,3);
plot(A(:,3));
subplot(4,1,4);
plot(A(:,4));
figure;
plot(A(:,1));hold;
plot(A(:,2));
plot(A(:,3));
legend('1','2','3');

% for numtry = 1:12
% 	X1 = A((10100+numtry*200):(10300+numtry*200),1);
% 	X2 = A((10100+numtry*200):(10300+numtry*200),2);
% 	X3 = A((10100+numtry*200):(10300+numtry*200),3);
% 
% 	y1 = fft(X1);
% 	y2 = fft(X2);
% 	y3 = fft(X3);
% 
% 	[~,p1] = max(abs(y1));
% 	[~,p2] = max(abs(y2));
% 	[~,p3] = max(abs(y3));
% 
% 	t1 = angle(y1(p1));
% 	t2 = angle(y2(p2));
% 	t3 = angle(y3(p3));
% 
% 	theta = atan((t3-t2)/(2*(t3-t1)-(t3-t2)));
% 	top = sign(t3-t2);
% 	bottom = sign(2*(t3-t1) - (t3-t2));
% 	if( top < 0 && bottom > 0)
% 			theta = theta+pi;
% 	end
% 	if( top > 0 && bottom > 0)
% 			theta = theta-pi;
% 	end
% 	degrees = theta*180/pi
% 
% end

index = 742702;
phase = zeros(1,60);
big_t1 = zeros(1,60);
big_t2 = zeros(1,60);
big_t3 = zeros(1,60);
for i = 1:60
	X1 = A(index+(i-1)*200:index+i*200,1);
	X2 = A(index+(i-1)*200:index+i*200,2);
	X3 = A(index+(i-1)*200:index+i*200,3);
% 	figure;hold;
% 	plot(X1);
% 	plot(X2);
% 	plot(X3);
	y1 = fft(X1);
	y2 = fft(X2);
	y3 = fft(X3);
	y1 = y1(2:50);
	y2 = y2(2:50);
	y3 = y3(2:50);
	[~,p1] = max(abs(y1));
	[~,p2] = max(abs(y2));
	[~,p3] = max(abs(y3));

	t1 = angle(y1(p1));
	t2 = angle(y2(p2));
	t3 = angle(y3(p3));
	theta = atan((t3-t2)/(2*(t3-t1)-(t3-t2)));
	top = sign(t3-t2);
	bottom = sign(2*(t3-t1) - (t3-t2));
	if( top < 0 && bottom > 0)
			theta = theta+pi;
	end
	if( top > 0 && bottom > 0)
			theta = theta-pi;
	end
	degrees = theta*180/pi;
	phase(i) = degrees;
	big_t1(i) = t1;
	big_t2(i) = t2;
	big_t3(i) = t3;
end
u_big_t1 = unwrap(big_t1);
u_big_t2 = unwrap(big_t2);
u_big_t3 = unwrap(big_t3);
for i = 1:60
	theta = atan((u_big_t3(i)-u_big_t2(i))/(2*(u_big_t3(i)-u_big_t1(i))-(u_big_t3(i)-u_big_t2(i))));
	top = sign(u_big_t3(i)-u_big_t2(i));
	bottom = sign(2*(u_big_t3(i)-u_big_t1(i)) - (u_big_t3(i)-u_big_t2(i)));
	if( top < 0 && bottom > 0)
			theta = theta+pi;
	end
	if( top > 0 && bottom > 0)
			theta = theta-pi;
	end
	degrees = theta*180/pi;
	u_phase(i) = degrees;
end
figure;
plot(phase);hold;
plot(u_phase,'--');
figure;
plot(unwrap(big_t1));
hold;
plot(unwrap(big_t2));
plot(unwrap(big_t3));
legend('t1','t2','t3');
mean(phase)
mean(u_phase)


% 
index = 69838;
X1 = A(index:index+50,1);
X2 = A(index:index+50,2);
X3 = A(index:index+50,3);
% X1 = A(1140+index:1230+index,1);
% X3 = A(1140+index:1230+index,3);
% X2 = A(1140+index:1230+index,2);
figure;hold;
plot(X1);
plot(X2);
plot(X3);
% legend('1','2','3');
y1 = fft(X1);
y2 = fft(X2);
y3 = fft(X3);
% plot(abs(y1));
y1 = y1(2:50);
y2 = y2(2:50);
y3 = y3(2:50);

[~,p1] = max(abs(y1));
[~,p2] = max(abs(y2));
[~,p3] = max(abs(y3));

t1 = angle(y1(p1));
t2 = angle(y2(p2));
t3 = angle(y3(p3));
theta = atan((t3-t2)/(2*(t3-t1)-(t3-t2)));
top = sign(t3-t2);
bottom = sign(2*(t3-t1) - (t3-t2));
if( top < 0 && bottom > 0)
		theta = theta+pi;
end
if( top > 0 && bottom > 0)
		theta = theta-pi;
end
degrees = theta*180/pi




X1 = A(:,1);
X2 = A(:,2);
X3 = A(:,3);

y1 = fft(X1);
y2 = fft(X2);
y3 = fft(X3);
y1 = y1(7000:100000);
y2 = y2(7000:100000);
y3 = y3(7000:100000);

[~,p1] = max(abs(y1));
[~,p2] = max(abs(y2));
[~,p3] = max(abs(y3));

t1 = angle(y1(p1));
t2 = angle(y2(p2));
t3 = angle(y3(p3));
theta = atan((t3-t2)/(2*(t3-t1)-(t3-t2)));
top = sign(t3-t2);
bottom = sign(2*(t3-t1) - (t3-t2));
if( top < 0 && bottom > 0)
		theta = theta+pi;
end
if( top > 0 && bottom > 0)
		theta = theta-pi;
end
degrees = theta*180/pi



% 
% freq = (0:length(A(:,1))-1)*500000/length(A(:,1));
% freq = freq(260000:300000);
% fft1 = fft(A(:,1));
% fft1 = fft1(260000:300000);
% fft2 = fft(A(:,2));
% fft2 = fft2(260000:300000);
% fft3 = fft(A(:,3));
% fft3 = fft3(260000:300000);
% fft4 = fft(A(:,4));
% fft4 = fft4(260000:300000);
% figure;
% subplot(4,1,1);
% plot(freq,abs((fft1)));
% subplot(4,1,2);
% plot(freq,abs((fft2)));
% subplot(4,1,3);
% plot(freq,abs((fft3)));
% subplot(4,1,4);
% plot(freq,abs((fft4)));